import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Elo7 | Technical Interaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200300400600700900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <h1>Estrutura Inicial</h1>
      </main>
    </>
  )
}

export default Home
